### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by ktaragorn** [xunker/AutoHideSidebar#2]
I am having a lot of trouble configuring this addon. I am not sure where to put the settings. I tried to create AutoHideSidebar.sublime-settings file, and putting there, didnt work. I put it in my preferences and it still doesnt work. 

I saw in the code that AutoHideSidebar file was loaded but it doesnt seem to be used.

I compulsively save files every few keys so I need to disable show on save setting.

**Comment by ktaragorn** [comment]
This is on ST3

**Comment by ktaragorn** [comment]
I believe I was facing an issue with https://forum.sublimetext.com/t/settings-not-reloading/11275/17 which might be why I was not getting my preferences loaded. The point about it loading `AutoHideSidebar.sublime-settings` but not using it still stands i think

**Comment by xunker** [comment]
Even though you closed this, I'll still check it out. Thank you for the bug report.

**Comment by ktaragorn** [comment]
Thanks @xunker, There is also an issue where the logic seems to reverse itself.. briefly, show becomes hide (hide immediately, show after 5 keystrokes) let me try to replicate and report.

**Comment by ktaragorn** [comment]
I believe it doesnt work well with command + shift + R which reveals the current file in the sidebar

**Comment by xunker** [comment]
When I originally wrote this, there was no way to query the state of the sidebar with the Sublime API. So if something else changed the sidebar state then this code started working in reverse.

There are functions in the API called [`is_sidebar_visible()` and `set_sidebar_visible(flag)`](https://www.sublimetext.com/docs/3/api_reference.html#sublime.Window). I don't know if I just missed them before or if they are new. They may also not do that I think. I'm going to explore them.

If I can't fix this properly, another idea I had been considering before is a command that would swap the internal state of the sidebar whenever this happened. It's not a perfect solution but it would allow you to fix the problem and keep on working.

**Comment by xunker** [comment]
Update: Confirmed, `is_sidebar_visible()` can query the state and `set_sidebar_visible(flag)` can absolutely set it. I think that changing to use those will break ST2 compatibility but I have never tried this on ST2 and I doubt anyone else is using it there.

I'm going to close this issue and continue the work in #3.
