### ISSUE TITLE
Show/Hide behavior flip after cmd+shift+R in ST3

### ISSUE THREAD

**Issue by ktaragorn** [xunker/AutoHideSidebar#3]
Steps to replicate
1. Auto hide the sidebar
2. Press CMD + Shift + R to show the side bar.

From now the behaviour becomes quite eratic until it either works itself out or I explicitly hide the sidebar.

For e.g At this point if I select a different file, the sidebar immediately hides and then Auto SHOWs when 5 characters are typed.

**Comment by xunker** [comment]
The fix will be to use `is_sidebar_visible()` and `and set_sidebar_visible(flag)` to replace the code I originally copied from SyncedSideBar.

For my own reference:
 * https://www.sublimetext.com/docs/3/api_reference.html#sublime.Window
 * https://forum.sublimetext.com/t/set-sidebar-visible-not-work/17467

**Comment by xunker** [comment]
Have found another, likely related issue:

Any text input anywhere, like in a panel (e.g. the command palette) or the console *also* is seen as a change and will show/hide the sidebar. Need to fix that too.

**Comment by ktaragorn** [comment]
Hey, any update for this? I am finding this addon quite unstable. It also seems to fight the sublime keys to show or hide the side bar (cmd +k, cmd + b)

**Comment by ktaragorn** [comment]
Can I help debug or even develop a fix for this? Should I look at the linked PR?

**Comment by ktaragorn** [comment]
@xunker Please take a look at #5, these are all the changes that you mentioned, and also fixed an issue with multiple windows and change counter

**Comment by ktaragorn** [comment]
From reading https://github.com/TheSpyder/SyncedSideBar I think that the apis we are looking at are recently, only in ST3, is this a problem?

**Comment by ktaragorn** [comment]
activated trigger even applies within the same window, with different rows/columns in a multi view layout, is this intentional?

**Comment by ktaragorn** [comment]
Hey, Can you make a release please? https://packagecontrol.io/packages/Auto%20Hide%20Sidebar doesnt yet have the fix
